config/routes.rb
RailsBook::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li<
        %a{:href => "http://news.railstutorial.org/"} News
      %li<
        %a{:href => "http://www.railstutorial.org/"} Rails Tutorial

app/views/layouts/_header.html.haml
%header
  = link_to logo, root_path
  %nav.round
    %ul
      %li= link_to "Home", root_path
      - if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Sign out", signout_path, :method => :delete
      - else
        %li= link_to "Sign in", signin_path

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
  %script{:src => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'blueprint/ie'
= stylesheet_link_tag 'custom', :media => 'screen'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= title
    = csrf_meta_tag
    = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
    = javascript_include_tag "rails"
    = render 'layouts/stylesheets'
  %body
    .container
      = render 'layouts/header'
      %section.round
        - flash.each do |key, value|
          = content_tag :div, value, :class => "flash #{key}"
        = yield
      = render 'layouts/footer'
      - if Rails.env.development?
        = debug(params)